# Render deployment specification for Community Library API (backend only)
# Docs: https://render.com/docs/yaml-spec
services:
  - type: web
    name: community-library-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install --production=false
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      # Set these sensitive values via dashboard/UI after first deploy
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://mighty-suz.github.io
