name: Deploy Backend (Clean Zip)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

concurrency:
  group: backend-clean-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Zip & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install production dependencies (npm ci)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --omit=dev
          else
            npm install --omit=dev
          fi
          node -p "'Express version: ' + require('./node_modules/express/package.json').version"

      - name: Create deployment package (include node_modules)
        run: |
          rm -rf tests coverage || true
            zip -r ../backend.zip . \
              -x "**/tests/**" "**/coverage/**" "**/.DS_Store" \
              -x "**/*.log" > /dev/null
          ls -lh ../backend.zip
          unzip -l ../backend.zip | grep server.js || true

      - name: Deploy via publish profile (skip Oryx build)
        uses: azure/webapps-deploy@v3
        with:
          app-name: community-library-backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: backend.zip
          enable-oryx-build: false

      - name: Post-deploy health check (retry)
        run: |
          for i in 1 2 3 4 5; do
            echo "Attempt $i";
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://community-library-backend.azurewebsites.net/api/health || true)
            if [ "$STATUS" = "200" ]; then
              curl -fsS https://community-library-backend.azurewebsites.net/api/health; exit 0; fi
            sleep 10;
          done
          echo "Health endpoint not reachable"; exit 1
