# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy backend (Azure) - community-library-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install production dependencies (backend only)
        working-directory: backend
        run: npm install --omit=dev

      - name: Package backend
        run: |
          cp -r backend dist-backend
          rm -rf dist-backend/tests dist-backend/coverage || true
          ls -al dist-backend
          zip -r backend.zip dist-backend > /dev/null

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: List downloaded files
        run: |
          echo "PWD: $(pwd)"
          ls -al
          ls -al *.zip || true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_387CD6DF61ED483D8DE452EF4FA732E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3A1ABFE190A4A51816D12F32F320BA5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_108843DFB06746C1919245BB49F7D22E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: community-library-backend
          slot-name: Production
          package: backend.zip
          